name: Deploy
on: [push]
jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: npm ci
        run: npm run build
        run: mv dist/index.html dist/404.html
        run: |
          echo "reksio - 4"
          git config --global user.email "`git log -1 --pretty=format:'%ae'`"
          echo "reksio - 5"
          git config --global user.name "`git log -1 --pretty=format:'%an'`"
          echo "reksio - 6"
          cd dist
          echo "reksio - 7"
          git init
          echo "reksio - 8"
          git add .
          echo "reksio - 9"
          git commit -m "deploy"
          echo "reksio - 10"
          git push --force git@github.com:noisy/personal.git gh-pages
