name: Deploy
on: [push]
jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
          mv dist/index.html dist/404.html
          mv dist docs
      - name: Publish
        run: |
          git config --global user.email "`git log -1 --pretty=format:'%ae'`"
          git config --global user.name "`git log -1 --pretty=format:'%an'`"
          git add .
          git commit -m "deploy"
          git push origin master:gh-pages -f
