name: Deploy
on: [push]
jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: mv dist/index.html dist/404.html
      - run: mv dist docs
      - run: git config --global user.email "`git log -1 --pretty=format:'%ae'`"
      - run: git config --global user.name "`git log -1 --pretty=format:'%an'`"
      - run: git add . && git commit -m "deploy" && git push --force git@github.com:noisy/personal.git master:gh-pages
