name: Deploy
on: [push]
jobs:
  deploy_prod:
    if: contains( github.ref, 'master')
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm ci
          npm run build
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add dist -f
          git commit -m "deploy"
          git subtree push --prefix dist origin gh-pages
